### ISSUE TITLE
Check box won't update

### ISSUE THREAD

**Issue by GavinJaynes** [tammyhart/Reusable-Custom-WordPress-Meta-Boxes#10]
Hi, I have zero issues with any other type but for some reason the checkbox won't update. Is anyone else experienced this?

I haven't tampered with metabox.php and below is the code for creating the specific metabox.   

<pre>
$featuredpost = array(
    array( // Text Input
        'label' => 'Display in Slider:', // <label>
        'desc'  => 'Is this a featured post', // description
        'id'    => $prefix.'featured_slider', // field id and name
        'type'  => 'checkbox' // type of field
    )
);

$featured_box = new custom_add_meta_box( 'featured', 'Featured Post', $featuredpost, $right_category, false );
</pre>

Any advice would be greatly appreciated.

**Comment by INVSBL-HND** [comment]
By adding a hidden input type with the same name as the checkbox input type only when the condition is true we can successfully check AND uncheck the meta field and save our value. Below is my code for the checkbox case.

```
case 'checkbox': 
    echo '<input type="checkbox" name="'.$field['id'].'" id="'.$field['id'].'" '.($meta ? 'checked="checked"/><input type="hidden" name="'.$field['id'].'"' : '').'/>';
break;
```

**Comment by tammyhart** [comment]
The new metabox_sanitize_boolean() function and proper use of the checked() function have fixed this.

**Comment by hugoassuncao** [comment]
I had the same problem, even when I did use the proper sanitize.
The code proposed by @ryanmaurodesign solved the problem.
