### ISSUE TITLE
Multi selection in selectbox

### ISSUE THREAD

**Issue by pixtest** [tammyhart/Reusable-Custom-WordPress-Meta-Boxes#12]
Does anyone getting issue in storing multiple selection of select box values in db. because when i have tried, it stores value as a single value, not as an array and the last value which i have selected is being stored in db.

**Comment by tammyhart** [comment]
this is fixed in the latest fix. You can also now add 'multiple' => true to your select, chosen, post_select and post_chosen field arrays to indicate a multiple select box
