### ISSUE TITLE
WP 3.5 Image Uploader Not Working

### ISSUE THREAD

**Issue by wesdekoninck** [tammyhart/Reusable-Custom-WordPress-Meta-Boxes#14]
After upgrading to WP 3.5, it looks like the image field uploader will no longer work because of how the new media uploader is supposed to be called.

Any ideas?

**Comment by tammyhart** [comment]
I haven't yet tackled the new media uploader, but I have just now updated the js to be compatible with 3.5 so that the current thickbox method is now working. I plan to fully upgrade to the new media uploader soon.

**Comment by nomoreme** [comment]
Hi!

the image field uploader doesn't seem to work on wp 3.5.1.

After clicking the "choose image" button, i get this error in the chrome console:

```
Uncaught ReferenceError: tb_show is not defined     scripts.js:8
(anonymous function)     scripts.js:8
v.event.dispatch     load-scripts.php:2
o.handle.u     load-scripts.php:2
```

How can i make it work?

Tnx

EDIT:
I've manage to show the upload box by manually enqueue the 'thickbox' script and style from my functions.php

**Comment by davshoward** [comment]
I'm getting a similar error as nomoreme:

Uncaught ReferenceError: wp is not defined scripts.js:20
(anonymous function) scripts.js:20
v.event.dispatch load-scripts.php:2
o.handle.u load-scripts.php:2

**Comment by ke6et** [comment]
same issue here :(
