### ISSUE TITLE
Images in Repeatable field saved with extra characters

### ISSUE THREAD

**Issue by kellygrape** [tammyhart/Reusable-Custom-WordPress-Meta-Boxes#17]
It seems that images in repeatable fields are saved with some extra code (from what I can tell, an extra **/>**, possibly a quote in there too). 

This doesn't cause any problems when trying to save or retrieve the values, but it does appear on the backend after everything is saved.

 I was able to resolve this in my recent fork, by adjusting line 206 in meta_box.php to use intval($meta) instead of just $meta. I wanted to see if there was a better solution before submitting a pull request. 

Thanks!

**Comment by tammyhart** [comment]
hmm.. the real problem probably lies in js/scripts.js around line 12, but that field should ahve intval anyways so good catch. I'll take another look at the js when I get a chance.

**Comment by tammyhart** [comment]
This is now fixed in the latest commit
