### ISSUE TITLE
Install problem: fatal error / Qustion about repeatable_id

### ISSUE THREAD

**Issue by Caspert** [tammyhart/Reusable-Custom-WordPress-Meta-Boxes#20]
Dear Tammy,

When I would like to install your source to my wordpress theme, I get an fatal error:
Fatal error: Cannot redeclare the_field() in metaboxes/meta_box.php on line 15

Line 15:
function the_field( $field, $meta = null, $repeatable = null ) {

Also I had the question where the class "repeatable_id" is declared, because you use this id for the repeatable javascript code...

```
    $('input.repeatable_id:text').each(function(){ arr.push($(this).val()); }); 
    clone.find('input.repeatable_id')
        .val(Number(Math.max.apply( Math, arr )) + 1);
    if (!!$.prototype.chosen) {
        clone.find('select.chosen')
            .chosen({allow_single_deselect: true});
    }
```

Thank you for advance.
Caspert

**Comment by tammyhart** [comment]
this is because I had originally put that function into the class which doesn't require unique namespacing, but then removed it without adding proper namespacing. I've fixed this in the latest commit. Thanks for pointing this out!
