### ISSUE TITLE
Add a metabox to a specific page (with a page-template) 

### ISSUE THREAD

**Issue by hwaal** [tammyhart/Reusable-Custom-WordPress-Meta-Boxes#22]
Hi there,

Is it possible to add different metaboxes to different pages? Lets say:

Homepage = 5 metaboxes (homepage-template.php) 
About page = 3 metaboxes  (about-template.php)

When I make a new page, I can select the page-template, update and then a specific metabox will show based on the chosen page-template. 

Thank you in advanced!

Huig

**Comment by tammyhart** [comment]
hwaal,

This isn't something that is built into the library here, but I have done it recently using this piece of code: https://gist.github.com/4543532

**Comment by hwaal** [comment]
Hi Tammy,

Great solution! Thank you very much!

Cheers

**Comment by vol4ikman** [comment]
Could you explain one more time (link is broken), how can I create metabox for a specific page template?

thanks
