### ISSUE TITLE
Bug remove image

### ISSUE THREAD

**Issue by Caspert** [tammyhart/Reusable-Custom-WordPress-Meta-Boxes#23]
Hello Tammy,

When I would like to remove my selected image, the field will not be clear.. I use the latest jQuery code of yours:
[code]
    // Delete uploaded image
    jQuery('.remove-image').click(function() {
        var defaultImage = $(this).parent().siblings('.default_image').text();
        jQuery(this).parent().siblings('.upload_image').val('');
        jQuery(this).parent().siblings('.preview_image').attr('src', defaultImage);
        return false;
    }); 
[/code]

**Comment by tammyhart** [comment]
are you getting any sort of jquery errors in your console?

**Comment by tammyhart** [comment]
I'm closing this thread since I cannot duplicate any bugs
