### ISSUE TITLE
post_type seems not to be correctly passed to post_list (and similar)

### ISSUE THREAD

**Issue by nomoreme** [tammyhart/Reusable-Custom-WordPress-Meta-Boxes#25]
When using the post_list, post_select or post_chosen i always get a list of post only and seems impossibile to change it and show pages or custom post type.

I've managed to solve the issue adding 

```
$post_type = isset( $field['post_type'] ) ? $field['post_type'] : null;
```

in meta_box.php, function the_field(), line 26, but i don't know if it's the right solution.

**Comment by tammyhart** [comment]
Yes, you were right about adding that. Funny that I missed it until now. I've fixed it in the latest commit. Thanks!
