### ISSUE TITLE
tax_checkboxes and tax_select won't work with hierarchical categories

### ISSUE THREAD

**Issue by nomoreme** [tammyhart/Reusable-Custom-WordPress-Meta-Boxes#26]
I have a custom_taxonomy that is hierarchical.

When i use either tax_checkboxes or tax_select it doesn't seem to work in the right way: if i choose one the child category, after saving the data, the parent category is selected (and saved, if the user press the update button)

**Comment by tammyhart** [comment]
I've set in a few conditionals that now check whether the taxonomy is hierarchical or not and saves the proper data accordingly.

**Comment by nomoreme** [comment]
Sorry, but i still have this issue :(

Now when I save, instead of saving the selected term, a new term is created (with the selected term-id as a name).

I've manage to solve the issue this way:

```
$term = intval($_POST[$field['id']]);
```

on line 590 of meta_box.php.

It seems to work in my case (it's a custom-taxonomy associated to a custom-post-type).

**Comment by davshoward** [comment]
@nomoreme - Thanks a bunch, I was having this issue as well.

**Comment by MarioGiancini** [comment]
Was having this issue to with just regular categories.  This fixed it. Thank you.
