### ISSUE TITLE
call to undefined function get_template_directory_uri() 

### ISSUE THREAD

**Issue by nidhig** [tammyhart/Reusable-Custom-WordPress-Meta-Boxes#27]
I kept metaboxes folder inside the theme folder and included the php file path in functions. php but when i run the file I receive above error. I am new to github and meta boxes. Any help to resolve the issue and to explain further would be highly appriciated. Thanks in advance

**Comment by tammyhart** [comment]
That is a WordPress core function that's been around since 1.5, so I'm not really sure what is going on here. I would make sure you're calling the meta_box.php in your theme's functions.php correctly.
