### ISSUE TITLE
Javascript for repeatable fields not being queued

### ISSUE THREAD

**Issue by helion** [tammyhart/Reusable-Custom-WordPress-Meta-Boxes#3]
It looks like back.js was created to replace the custom-js.js file used in the tutorials at wp.tutsplus.com but it looks like the bits relevant to repeatable fields weren't copied over.

Since custom-js.js isn't being queued anymore that means there's nothing to run when the repeatable field buttons get clicked.

**Comment by tammyhart** [comment]
This has been fixed with version 0.2
