### ISSUE TITLE
Problem with 2posttype metabox

### ISSUE THREAD

**Issue by EWSEL** [tammyhart/Reusable-Custom-WordPress-Meta-Boxes#31]
I have a problem I try using just the metabox in two posttype in one i use DatePicker and in one repeatable Fields therefore have 2 file created and post type for each metabox the problem is it show in all posttype only Datepicker and not repeatable Fields 

My qustion how can i use different metabox fields in different posttype ????

**Comment by tammyhart** [comment]
you should instantiate a new meta box for each post type.

**Comment by EWSEL** [comment]
I have made ​​but it show same metabox in all posttype

Herer is my code
http://pastebin.com/msvm1FEK ->Metabox Downloads
http://pastebin.com/k83pN6xM ->Metabox Movie

**Comment by tammyhart** [comment]
It looks like you're still using code from my original tutorial. I suggest you update to using the new code found in this repo. The class is a lot easier to use and if you stay up to do date with changes I  make here, you'll get new features as I add and expand the capabilities.

After you've updated the code you're including in your theme or plugin, see the part of the read me with the title"Instantiate the class with all required variables"
