### ISSUE TITLE
issue with post list field and multiple post types

### ISSUE THREAD

**Issue by pdewouters** [tammyhart/Reusable-Custom-WordPress-Meta-Boxes#33]
<pre>   
array( // Post ID select box
        'label' => 'Post List', // <label>
        'desc'  => 'A description for the field.', // description
        'id'    =>  $prefix.'post_id', // field id and name
        'type'  => 'post_select', // type of field
        'post_type' => array('post','page') // post types to display, options are prefixed with their post type
    ),
</pre>

In the sample.php you're creating this field, and passing a post_type array, but in the code, you are not checking for an array. I think you need to use a foreach on the $post_type variable

**Comment by tammyhart** [comment]
This item is used to provide a list of posts. It uses get_posts to do so which is a wrapper for the WP_Query class which accepts either a string or array of post types. See: http://codex.wordpress.org/Class_Reference/WP_Query#Type_Parameters

**Comment by pdewouters** [comment]
Sorry, I should have been more explicit :)
With debug on, I get the following warning:

<pre>
 Notice: Trying to get property of non-object in E:\paul_docs\Websites\www.example.dev\wp-content\plugins\leadpress\includes\metaboxes\meta_box.php on line 117</pre>

On line 116, you're assigning

<pre>$post_type_object = get_post_type_object( $post_type );</pre>

but in the case of the Post List field, $post_type is an array if multiple post types are used in the field definition

**Comment by tammyhart** [comment]
ah, you're right. hmm, I'll put my thinking cap on for how to fix this. That is only needed for the description's "manage" link, so it shouldn't be too difficult.

**Comment by pdewouters** [comment]
do you accept pull requests?

**Comment by tammyhart** [comment]
Yes I do
