### ISSUE TITLE
NONCE index error

### ISSUE THREAD

**Issue by wesdekoninck** [tammyhart/Reusable-Custom-WordPress-Meta-Boxes#4]
When using this script to create multiple meta boxes, I was throwing errors related to the nonce and it looks like you are not checking to see if the nonce is set in addition to verifying it.

I was able to solve the issue by changing the following in meta_box.php:

Change this:

``` php
// verify nonce
if (!wp_verify_nonce($_POST[$page.'_meta_box_nonce'], basename(__FILE__))) 
      return $post_id;
```

To This:

``` php
// if nonce exists, verify nonce
if ( !isset( $_POST[$page.'_meta_box_nonce'] ) || !wp_verify_nonce( $_POST[$page.'_meta_box_nonce'], basename( __FILE__ )))
    return $post_id;
```

**Comment by tammyhart** [comment]
this has been fixed. thanks.
