### ISSUE TITLE
tcnmy_find_field_type

### ISSUE THREAD

**Issue by miharekar** [tammyhart/Reusable-Custom-WordPress-Meta-Boxes#5]
I get this error when I include this `Call to undefined function tcnmy_find_field_type()  in .../metaboxes/meta_box.php on line 33`

**Comment by tammyhart** [comment]
this has been fixed and replaced with the correct function name.

**Comment by miharekar** [comment]
Cool, thanks. But in the mean time, I made my own [meta box library](https://github.com/mrfoto/mr-meta-box) :smile:
