### ISSUE TITLE
Trouble getting 'Taxonomy Select Box' data

### ISSUE THREAD

**Issue by ProgressionStudios** [tammyhart/Reusable-Custom-WordPress-Meta-Boxes#7]
How do I get the 'Taxonomy Select Box' data? 

I can pull all the other data fields easily via get_post_meta like so:
<?php echo get_post_meta($post->ID, 'sample_text', true) ?>

However I am having trouble referencing the Taxonomy Select Box data.  I assume I'm missing something simple but am lost.  

What would be the code to echo the selected taxonomy category name or ID? When I use the <?php the_meta(); ?> tag, I don't see any data being displayed for the taxonomy select. 

PS.  Thanks for the great tutorial and sharing your code.

**Comment by tammyhart** [comment]
Taxonomies don't get saved to the post meta, they get set just like any other taxonomy would (categories, tags, etc.) You can use any of the WordPress functions for getting terms for a post.

**Comment by ProgressionStudios** [comment]
Awesome, I get it now. I knew it was going to be something simple. Thanks for the quick reply and keep up the good work.
